name: Mac MPS

on:
  # push:
  #   tags:
  #     - ciflow/mps/*
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 6 * * *' # run at 6:00 AM UTC (11 PM UTC)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  macos-py39-arm64-build:
    name: macos-py39-arm64
    uses: ./.github/workflows/_mac-build.yml
    with:
      sync-tag: macos-py39-arm64-build
      build-environment: macos-py39-arm64
      xcode-version: "13.3.1"
      runner-type: macos-builder
      build-generates-artifacts: true
      # To match the one pre-installed in the m1 runners
      python_version: 3.9.12
      # We need to set the environment file here instead of trying to detect it automatically because
      # MacOS arm64 is cross-compiled from x86-64. Specifically, it means that arm64 conda environment
      # is needed when building PyTorch MacOS arm64 from x86-64
      environment-file: .github/requirements/conda-env-macOS-ARM64
    secrets:
      MACOS_SCCACHE_S3_ACCESS_KEY_ID: ${{ secrets.MACOS_SCCACHE_S3_ACCESS_KEY_ID }}
      MACOS_SCCACHE_S3_SECRET_ACCESS_KEY: ${{ secrets.MACOS_SCCACHE_S3_SECRET_ACCESS_KEY }}

  macos-py38-arm64-build:
    name: macos-py38-arm64
    uses: ./.github/workflows/_mac-build.yml
    with:
      sync-tag: macos-py38-arm64-build
      build-environment: macos-py38-arm64
      xcode-version: "13.3.1"
      runner-type: macos-builder
      build-generates-artifacts: true
      # To match the one pre-installed in the m1 runners
      python_version: 3.8
      # We need to set the environment file here instead of trying to detect it automatically because
      # MacOS arm64 is cross-compiled from x86-64. Specifically, it means that arm64 conda environment
      # is needed when building PyTorch MacOS arm64 from x86-64
      environment-file: .github/requirements/conda-env-macOS-ARM64
    secrets:
      MACOS_SCCACHE_S3_ACCESS_KEY_ID: ${{ secrets.MACOS_SCCACHE_S3_ACCESS_KEY_ID }}
      MACOS_SCCACHE_S3_SECRET_ACCESS_KEY: ${{ secrets.MACOS_SCCACHE_S3_SECRET_ACCESS_KEY }}

  macos-12_5-py3-arm64-mps-test:
    name: macos-12.5-py3-arm64-mps
    uses: ./.github/workflows/_mac-test-mps.yml
    needs: macos-py39-arm64-build
    with:
      sync-tag: macos-py39-arm64-mps-test
      build-environment: macos-py39-arm64
      runs-on: macos-arm-12.5

  macos-13_2-py3-arm64-mps-test:
    name: macos-13.2-py3-arm64-mps
    uses: ./.github/workflows/_mac-test-mps.yml
    needs: macos-py39-arm64-build
    with:
      build-environment: macos-py39-arm64
      runs-on: macos-arm-13.2

  macos-13_3-py3-arm64-mps-test:
    name: macos-13.3-py3-arm64-mps
    uses: ./.github/workflows/_mac-test-mps.yml
    needs: macos-py39-arm64-build
    with:
      build-environment: macos-py39-arm64
      runs-on: macos-arm-13.3
